[tool.ruff]
# Enable ruff rules to act like flake8
lint.select = [
    "E",  # pycodestyle (formerly part of flake8)
    "F",  # pyflakes (formerly part of flake8)
    "I",  # import order (like isort)
    # "B",  # flake8-bugbear
    "C90",  # flake8-comprehensions
]

line-length = 120
indent-width = 4
target-version = "py39"

# Exclude specific rules if needed
lint.ignore = [
    "E501",  # Ignore line length (similar to flake8's max-line-length)
]
