apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: ${APP_NAME}

    spec:
      envName: ${ENV_NAME}

      dependencies:
        - host-inventory
        - rbac

      database:
        name: ${DB_NAME}
        version: 16

      deployments:
        - name: roadmap-api  # Would changing this to just API break 3scale?
          minReplicas: ${{MIN_REPLICAS}}
          deploymentStrategy:
            privateStrategy: RollingUpdate

          webServices:
            public:
              enabled: true
              apiPath: ${APP_NAME}

          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            env:
              - name: APP_NAME
                value: ${APP_NAME}

              - name: ROADMAP_HOST_INVENTORY_URL
                value: ${ROADMAP_HOST_INVENTORY_URL}

              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: sentry
                    key: dsn
                    optional: true

              - name: SENTRY_ENVIRONMENT
                value: ${ENV_NAME}

            resources:
              limits:
                cpu: "${CPU_LIMIT_SERVICE}"
                memory: "${MEMORY_LIMIT_SERVICE}"

              requests:
                cpu: ${CPU_REQUEST_SERVICE}
                memory: ${MEMORY_REQUEST_SERVICE}

            livenessProbe:
              httpGet:
                path: /api/roadmap/v1/ping
                port: ${{WEB_PORT}}
              initialDelaySeconds: 15
              periodSeconds: 10
              failureThreshold: 6

            readinessProbe:
              httpGet:
                path: /api/roadmap/v1/ping
                port: ${{WEB_PORT}}
              initialDelaySeconds: 15
              periodSeconds: 10
              failureThreshold: 6

      jobs:
        - name: inventory-sync
          restartPolicy: Never
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            env:
              - name: LOG_LEVEL
                value: ${LOG_LEVEL}

              - name: DB_SSL_MODE
                value: ${DB_SSL_MODE}

              - name: CLOWDER_ENABLED
                value: "true"

              - name: HBI_PUBLICATION
                value: hbi_hosts_pub_v1_0_0

              - name: HBI_SUBSCRIPTION
                value: ${APP_NAME}_hosts_sub

              - name: ALTER_SUBSCRIPTION
                value: ${ALTER_SUBSCRIPTION}

              - name: DROP_SUBSCRIPTION
                value: ${DROP_SUBSCRIPTION}

              - name: DROP_HBI_TABLE
                value: ${DROP_HBI_TABLE}

              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${ROADMAP_DB_SECRET_NAME}
                    key: db.name

            args:
              - /opt/venvs/replication/bin/python
              - /usr/local/bin/replication.py

            resources:
              limits:
                cpu: ${CPU_LIMIT_INVENTORY_SYNC}
                memory: ${MEMORY_LIMIT_INVENTORY_SYNC}

              requests:
                cpu: ${CPU_REQUEST_INVENTORY_SYNC}
                memory: ${MEMORY_REQUEST_INVENTORY_SYNC}

            database:
              sharedDbAppName: ${DB_NAME}

            volumeMounts:
              - name: host-inventory-db
                mountPath: /etc/db/hbi
                readOnly: true

              - name: rds-client-ca
                mountPath: /etc/db/rdsclientca
                readOnly: true

            volumes:
              - name: host-inventory-db
                secret:
                  secretName: host-inventory-db
                  optional: true
                  items:
                    - key: db.host
                      path: db_host

                    - key: db.name
                      path: db_name

                    - key: db.password
                      path: db_password

                    - key: db.port
                      path: db_port

                    - key: db.user
                      path: db_user

              - name: rds-client-ca
                secret:
                  secretName: rds-client-ca
                  optional: true
                  items:
                    - key: rds-cacert
                      path: rds_cacert

  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      name: inventory-sync-${INVENTORY_SYNC_COUNTER}

    spec:
      appName: ${APP_NAME}
      jobs:
        - inventory-sync

parameters:
  - name: IMAGE_TAG
    description: Image tag
    required: true
    value: latest

  - name: IMAGE
    description: Image name
    value: quay.io/redhat-services-prod/rhel-lightspeed-tenant/roadmap

  - name: ENV_NAME
    required: true

  - name: MIN_REPLICAS
    description: Replica count for backend service
    value: "3"

  - name: APP_NAME
    value: roadmap
    required: true

  - name: WEB_PORT
    description: Port this is running on
    value: "8000"

  - name: MEMORY_LIMIT_SERVICE
    value: 2048Mi

  - name: MEMORY_REQUEST_SERVICE
    value: 1024Mi

  - name: CPU_LIMIT_SERVICE
    value: "2"

  - name: CPU_REQUEST_SERVICE
    value: "1"

  - name: ROADMAP_DB_SECRET_NAME
    value: roadmap-db

  - name: DB_NAME
    required: true
    value: roadmap

  - name: ROADMAP_HOST_INVENTORY_URL

  - name: CPU_REQUEST_INVENTORY_SYNC
    value: 250m

  - name: CPU_LIMIT_INVENTORY_SYNC
    value: 500m

  - name: MEMORY_REQUEST_INVENTORY_SYNC
    value: 256Mi

  - name: MEMORY_LIMIT_INVENTORY_SYNC
    value: 512Mi

  - name: DB_SSL_MODE
    value: prefer

  - name: ALTER_SUBSCRIPTION
    value: ''

  - name: DROP_SUBSCRIPTION
    value: ''

  - name: DROP_HBI_TABLE
    value: ''

  - name: INVENTORY_SYNC_COUNTER
    value: '1'

  - name: LOG_LEVEL
    value: DEBUG
